---
title: "Impact of missing values on Support Vector Machines"
author: "Aurèle Bartolomeo"
date: "10/07/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

# R setup and imports
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(reticulate)
library(ggplot2)
```

# Python setup and imports
```{python}
# to install, py_install("package") or py_install("package", pip=TRUE)
from sklearn.datasets import make_classification
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

```



# Simulations

```{python}

# useful functions

def generate_data(n_samples, n_informative, n_features, n_redundant, random_state):
  X, Y = make_classification(n_samples=int(n_samples), n_informative=int(n_informative),
    n_features=int(n_features), flip_y=0.01, n_redundant=int(n_redundant), n_clusters_per_class=1, random_state = int(random_state), class_sep=0.8)
  return (X, Y)


def mask_data_mnar1(X, prob1=0.2, prob2=0.5):
  X = X.copy()
  n = len(X)
  p = len(X[0])
  q1 = np.quantile(X, q=prob1)
  q2 = np.quantile(X, q=prob2)
  mask = []
  for i in range(n):
    mask_line = []
    for j in range(p):
      if(X[i,j]<= q1 or X[i,j] >= q2):
        arr = 1
      else:
        arr = 0
    
      mask_line = np.append(mask_line, arr)
    mask.append(mask_line)

  X[np.array(mask).astype(bool)]=None
  return X

def mask_data_mnar2(X, prob1=0.2, prob2=0.5):
  X = X.copy()
  n = len(X)
  p = len(X[0])
  q1 = np.quantile(X, q=prob1)
  q2 = np.quantile(X, q=prob2)
  mask = []
  for i in range(n):
    mask_line = []
    for j in range(p):
      if(X[i,j]>= q1 and X[i,j]<=q2):
        arr = 1
      else:
        arr = 0
    
      mask_line = np.append(mask_line, arr)
    mask.append(mask_line)

  X[np.array(mask).astype(bool)]=None
  return X
  

def svcPerf(X_train, X_test, y_train, y_test):
  svc = SVC()
  svc.fit(X_train, y_train)
  return svc.score(X_test, y_test)
  

```



```{r}
run_simulation = function(n = 1000,
                          n_it = 100,
                          prob = NULL) {
  results = data.frame()
  
  for (p in prob) {
    
    perf_mean_MNAR1 = c("MNAR1", "mean", p)
    perf_mean_MNAR2 = c("MNAR2", "mean", p)
    
    perf_reg_MNAR1 = c("MNAR1", "reg", p)
    perf_reg_MNAR2 = c("MNAR2", "reg", p)
    
    perf_s_reg_MNAR1 = c("MNAR1", "s_reg", p)
    perf_s_reg_MNAR2 = c("MNAR2", "s_reg", p)
    
    perf_mi5_MNAR1 = c("MNAR1", "mi5", p)
    perf_mi5_MNAR2 = c("MNAR2", "mi5", p)
    
    perf_mi15_MNAR1 = c("MNAR1", "mi15", p)
    perf_mi15_MNAR2 = c("MNAR2", "mi15", p)
    
    
    for (i in 1:n_it) {
      
      XY = py$generate_data(
        n_samples = n,
        n_informative = 8,
        n_features = 10,
        n_redundant = 2,
        random_state = i
      )
      X = XY[[1]]
      Y = XY[[2]]
      
      X_NA_MNAR1 = py$mask_data_mnar1(X, prob1 = p/2, prob2 = 1-p/2)
      X_NA_MNAR2 = py$mask_data_mnar2(X, prob1 = 1/2 - p/2, prob2 = 1/2 + p/2)
      
      #train test split
      
      splitted_MNAR1 = py$train_test_split(X_NA_MNAR1,
                                     Y,
                                     test_size = 0.2,
                                     random_state = as.integer(i))
      X_train_MNAR1 = splitted_MNAR1[[1]]
      X_test_MNAR1 = splitted_MNAR1[[2]]
      y_train_MNAR1 = splitted_MNAR1[[3]]
      y_test_MNAR1 = splitted_MNAR1[[4]]
      
      splitted_MNAR2 = py$train_test_split(X_NA_MNAR2,
                                     Y,
                                     test_size = 0.2,
                                     random_state = as.integer(i))
      X_train_MNAR2 = splitted_MNAR2[[1]]
      X_test_MNAR2 = splitted_MNAR2[[2]]
      y_train_MNAR2 = splitted_MNAR2[[3]]
      y_test_MNAR2 = splitted_MNAR2[[4]]
      

      #mean
      
      
      X_train_mean_MNAR1 = mice::complete(mice::mice(
        X_train_MNAR1,
        method = "mean",
        m = 1,
        maxit = 1
      ))
      
      X_test_mean_MNAR1 = mice::complete(mice::mice(
        X_test_MNAR1,
        method = "mean",
        m = 1,
        maxit = 1
      ))
      
      perf_mean_MNAR1 = append(perf_mean_MNAR1,
                         py$svcPerf(X_train_mean_MNAR1, X_test_mean_MNAR1, y_train_MNAR1, y_test_MNAR1))
      
      
      X_train_mean_MNAR2 = mice::complete(mice::mice(
        X_train_MNAR2,
        method = "mean",
        m = 1,
        maxit = 1
      ))
      
      X_test_mean_MNAR2 = mice::complete(mice::mice(
        X_test_MNAR2,
        method = "mean",
        m = 1,
        maxit = 1
      ))
      
      perf_mean_MNAR2 = append(perf_mean_MNAR2,
                         py$svcPerf(X_train_mean_MNAR2, X_test_mean_MNAR2, y_train_MNAR2, y_test_MNAR2))
      
      
      #reg
      
      X_train_reg_MNAR1 = mice::complete(mice::mice(X_train_MNAR1, method = "norm.predict", m =
                                             1))
      
      X_test_reg_MNAR1 = mice::complete(mice::mice(X_test_MNAR1, method = "norm.predict", m =
                                             1))
      
      perf_reg_MNAR1 = append(perf_reg_MNAR1,
                        py$svcPerf(X_train_reg_MNAR1, X_test_reg_MNAR1, y_train_MNAR1, y_test_MNAR1))
      
      
      
      X_train_reg_MNAR2 = mice::complete(mice::mice(X_train_MNAR2, method = "norm.predict", m =
                                             1))
      
      X_test_reg_MNAR2 = mice::complete(mice::mice(X_test_MNAR2, method = "norm.predict", m =
                                             1))
      
      perf_reg_MNAR2 = append(perf_reg_MNAR2,
                        py$svcPerf(X_train_reg_MNAR2, X_test_reg_MNAR2, y_train_MNAR2, y_test_MNAR2))
      
      
      #s_reg
       
      X_train_s_reg_MNAR1 = mice::complete(mice::mice(X_train_MNAR1, method = "norm.nob", m = 1))
      
      X_test_s_reg_MNAR1 = mice::complete(mice::mice(X_test_MNAR1, method = "norm.nob", m = 1))
      
      perf_s_reg_MNAR1 = append(
        perf_s_reg_MNAR1,
        py$svcPerf(
          X_train_s_reg_MNAR1,
          X_test_s_reg_MNAR1,
          y_train_MNAR1,
          y_test_MNAR1
        )
      )
      
      
      X_train_s_reg_MNAR2 = mice::complete(mice::mice(X_train_MNAR2, method = "norm.nob", m = 1))
      
      X_test_s_reg_MNAR2 = mice::complete(mice::mice(X_test_MNAR2, method = "norm.nob", m = 1))
      
      perf_s_reg_MNAR2 = append(
        perf_s_reg_MNAR2,
        py$svcPerf(
          X_train_s_reg_MNAR2,
          X_test_s_reg_MNAR2,
          y_train_MNAR2,
          y_test_MNAR2
        )
      )
      

      #mi5
      
      X_train_mi5_MNAR1 = mice::complete(mice::mice(X_train_MNAR1, m = 5, maxit = 5))
      
      X_test_mi5_MNAR1 = mice::complete(mice::mice(X_test_MNAR1, m = 5, maxit = 5))
      
      perf_mi5_MNAR1 = append(perf_mi5_MNAR1,
                       py$svcPerf(X_train_mi5_MNAR1, X_test_mi5_MNAR1, y_train_MNAR1, y_test_MNAR1))
      
      
      X_train_mi5_MNAR2 = mice::complete(mice::mice(X_train_MNAR2, m = 5, maxit = 5))
      
      X_test_mi5_MNAR2 = mice::complete(mice::mice(X_test_MNAR2, m = 5, maxit = 5))
      
      perf_mi5_MNAR2 = append(perf_mi5_MNAR2,
                       py$svcPerf(X_train_mi5_MNAR2, X_test_mi5_MNAR2, y_train_MNAR2, y_test_MNAR2))
      

      #mi15
      
      X_train_mi15_MNAR1 = mice::complete(mice::mice(X_train_MNAR1, m = 15, maxit = 5))
      
      X_test_mi15_MNAR1 = mice::complete(mice::mice(X_test_MNAR1, m = 15, maxit = 5))
      
      perf_mi15_MNAR1 = append(perf_mi15_MNAR1,
                       py$svcPerf(X_train_mi15_MNAR1, X_test_mi15_MNAR1, y_train_MNAR1, y_test_MNAR1))
      
      
      
      X_train_mi15_MNAR2 = mice::complete(mice::mice(X_train_MNAR2, m = 15, maxit = 5))
      
      X_test_mi15_MNAR2 = mice::complete(mice::mice(X_test_MNAR2, m = 15, maxit = 5))
      
      perf_mi15_MNAR2 = append(perf_mi15_MNAR2,
                       py$svcPerf(X_train_mi15_MNAR2, X_test_mi15_MNAR2, y_train_MNAR2, y_test_MNAR2))
      
      

      
      
      
    }
    results = rbind(results, perf_mean_MNAR1, perf_mean_MNAR2,
                    perf_reg_MNAR1, perf_reg_MNAR2,
                    perf_s_reg_MNAR1, perf_s_reg_MNAR2,
                    perf_mi5_MNAR1, perf_mi5_MNAR2,
                    perf_mi15_MNAR1, perf_mi15_MNAR2)
    
    
  }
  write.table(results,"./new_results.csv", sep=",", row.names = FALSE, col.names=FALSE)
}
```

```{r}
start_time = Sys.time()
perfs = run_simulation(n=1000, n_it=1000,  prob = c(0.1, 0.2, 0.3, 0.4))
end_time = Sys.time()
```


```{r}
end_time - start_time
```
